@startuml

package "CIE-CNS Auto Login Token API (OSGi Bundle)" {
	component "A.1" {
		it.smc.labs.bootcamp.liferay.security.auto.login.token.configuration.CieCnsTokenAutoLoginConfiguration

		interface it.smc.labs.bootcamp.liferay.security.auto.login.token.configuration.CieCnsTokenAutoLoginConfiguration {
			+ String PID
			+ boolean enabled()
			+ boolean importFromExternalSource()
			+ String userTokenName()
			+ String originHttpHeaderName()
			+ String[] originHttpHeaderValues()
			+ String[] whitelist()
			+ boolean xForwarded()
			+ String tokenLocation()
		}
	}
}

@enduml